### ISSUE TITLE
Roblox constantly crashing

### ISSUE THREAD

**Issue by Elpersonn** [vinegarhq/vinegar#214]
I was trying to launch roblox today but it kept crashing and giving me the message about giving me a binary dump.
OS: Arch linux

What I've tried:

- Re-creating the wine prefix
- reinstalling roblox
- restarting
- switching wine-staging to normal wine
- Switching from DXVK to Vulkan

<details>

<summary>Crash log</summary>

```
2023/10/17 20:09:58 version.go:74: Fetching latest version of WindowsPlayer for channel live (https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/)
2023/10/17 20:09:59 version.go:94: Fetched WindowsPlayer canonical version 0.598.0.5980624
2023/10/17 20:09:59 version.go:55: Found WindowsPlayer version version-57e2dd886e0e42a5
2023/10/17 20:09:59 binary.go:137: WindowsPlayer is up to date (version-57e2dd886e0e42a5)
2023/10/17 20:09:59 fflags.go:88: Using renderer: Vulkan
2023/10/17 20:09:59 fflags.go:33: Applying custom FFlags
2023/10/17 20:09:59 fflags.go:51: FFlags used: {
  "DFIntTaskSchedulerTargetFps": 144,
  "FFlagDebugGraphicsDisableD3D11": true,
  "FFlagDebugGraphicsDisableD3D11FL10": true,
  "FFlagDebugGraphicsDisableOpenGL": true,
  "FFlagDebugGraphicsDisableVulkan": false,
  "FFlagDebugGraphicsPreferD3D11": false,
  "FFlagDebugGraphicsPreferD3D11FL10": false,
  "FFlagDebugGraphicsPreferOpenGL": false,
  "FFlagDebugGraphicsPreferVulkan": true
}
2023/10/17 20:09:59 dxvk.go:20: Enabling DXVK DLL overrides
2023/10/17 20:09:59 binary.go:66: Launching WindowsPlayer
2023/10/17 20:09:59 exec.go:24: Starting command: /usr/bin/wine /home/elperson/.local/share/vinegar/prefix/vinegar/versions/version-57e2dd886e0e42a5/RobloxPlayerBeta.exe
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (126).
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
00cc:fixme:ntdll:NtRaiseHardError c0000005 stub
2023/10/17 20:10:01 binary.go:87: Waiting for Roblox's process to die :)
2023/10/17 20:10:04 prefix.go:28: Killing wineprefix
2023/10/17 20:10:04 exec.go:30: Running command: /usr/bin/wineserver -k
```

</details>

**Comment by apprehensions** [comment]
Seems to me that Roblox or the wineprefix may already be running

**Comment by awesfdawe** [comment]
What version of wine are you using? If it's 8.18, then try downgrading to 8.15

Since you're an arch user, here are the commands:
```
pacman -R wine
pacman -U https://archive.archlinux.org/packages/w/wine-staging/wine-staging-8.15-1-x86_64.pkg.tar.zst
Or if u prefer normal wine
pacman -U https://archive.archlinux.org/packages/w/wine/wine-8.15-1-x86_64.pkg.tar.zst
```

**Comment by Davilarek** [comment]
doesn't help, vinegar built from source
wine-staging 8.15-1,
empty config
```
2023/11/04 13:38:06 logs.go:27: Logging to file: /home/davil/.cache/vinegar/logs/Player-2023-11-04T13:38:06+01:00.log
2023/11/04 13:38:06 version.go:45: Fetching latest version of WindowsPlayer for channel live
2023/11/04 13:38:06 api.go:22: Performing Roblox API GET clientsettings request on v2/client-version/WindowsPlayer/channel/live
2023/11/04 13:38:16 version.go:52: Fetched WindowsPlayer canonical version 0.601.0.6010507
2023/11/04 13:38:16 version.go:31: Got WindowsPlayer version version-6f0b02756d914e3e with channel live
2023/11/04 13:38:16 binary.go:241: WindowsPlayer is up to date (version-6f0b02756d914e3e)
2023/11/04 13:38:16 fflags.go:85: Using renderer: D3D11
2023/11/04 13:38:16 fflags.go:30: Applying custom FFlags
2023/11/04 13:38:16 dxvk.go:20: Enabling WINE DXVK DLL overrides
2023/11/04 13:38:16 discordrpc.go:16: Authenticating Discord RPC
2023/11/04 13:38:16 binary.go:122: Launching WindowsPlayer
2023/11/04 13:38:16 cmd.go:74: Starting command: /usr/bin/wine /home/davil/.local/share/vinegar/prefix/vinegar/versions/version-6f0b02756d914e3e/RobloxPlayerBeta.exe
esync: up and running.
002c:fixme:winediag:LdrInitializeThunk wine-staging 8.15 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (126).
0088:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0088:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0088:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0088:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0114:fixme:ntdll:NtRaiseHardError c0000005 stub
2023/11/04 13:38:21 prefix.go:34: Killing wineprefix
2023/11/04 13:38:21 cmd.go:74: Starting command: /usr/bin/wineserver -k
2023/11/04 13:38:21 discordrpc.go:21: Deauthenticating Discord RPC
2023/11/04 13:38:21 vinegar.go:177: roblox process: exit status 4
2023/11/04 13:38:30 vinegar.go:162: splash: window closed
2023/11/04 13:38:30 binary.go:110: Killing Roblox
^C
```

**Comment by awesfdawe** [comment]
@Davilarek Try changing wine-staging to some custom build, like wine ge. That worked for me, until recently everything worked fine on 8.15

**Comment by lunarlettuce** [comment]
Should be solved by Roblox upstream.
